---

- name: Setup acme-tiny and certificate request
  become: True
  include: setup.yml
  when: not ansible_user == acme_tiny__user_name

- name: Run acme-tiny
  become: True
  become_user: '{{ acme_tiny__user_name }}'
  shell: 'acme-tiny --account-key {{ acme_tiny__config_dir }}/{{ acme_tiny__account_key }} --csr {{ acme_tiny__cert_request }} --acme-dir {{ acme_tiny__challenge_dir }} > {{ acme_tiny__certificate }}'
  register: acme_tiny__register_certificate
  failed_when: False

- name: Show acme-tiny output
  debug: var=acme_tiny__register_certificate
  failed_when: not acme_tiny__register_certificate.rc == 0

- name: Certificate permissions
  file:
    path: '{{ acme_tiny__certificate }}'
    owner: '{{ acme_tiny__user_name }}'
    group: '{{ acme_tiny__user_group }}'
    mode: '0644'

- block:
    - name: Create lighttpd certificate
      shell: 'cat {{ acme_tiny__private_key }} {{ acme_tiny__certificate }} > {{ acme_tiny__cert_dir }}/{{ acme_tiny__cert_name }}_lighttpd.crt'

    - name: Fix lighttpd certificate permissions
      file:
        path: '{{ acme_tiny__cert_dir }}/{{ acme_tiny__cert_name }}_lighttpd.crt'
        owner: '{{ acme_tiny__user_name }}'
        group: '{{ acme_tiny__user_group }}'
        mode: '0600'

  when: (acme_tiny__cert_type == 'lighttpd') or
        ('lighttpd' in acme_tiny__cert_type)

- block:
    - name: Create postfix certificate
      shell: 'cat {{ acme_tiny__certificate }} {{ acme_tiny__config_dir }}/{intermediate.crt,ca.crt} > {{ acme_tiny__cert_dir }}/{{ acme_tiny__cert_name }}_postfix.crt'

    - name: Fix postfix certificate permissions
      file:
        path: '{{ acme_tiny__cert_dir }}/{{ acme_tiny__cert_name }}_postfix.crt'
        owner: '{{ acme_tiny__user_name }}'
        group: '{{ acme_tiny__user_group }}'
        mode: '0644'

  when: (acme_tiny__cert_type == 'postfix') or
        ('postfix' in acme_tiny__cert_type)

- name: Restart service
  command: sudo -n /usr/bin/systemctl restart '{{ item }}'
  register: acme_tiny__register_service_restart
  with_items: '{{ acme_tiny__cert_type
                  if acme_tiny__cert_type is iterable and not acme_tiny__cert_type is string
                  else [ acme_tiny__cert_type ] }}'
