---

- name: Certificate renewal group
  group:
    name: '{{ acme_tiny__user_group }}'
    system: True

- name: Certificate renewal user
  user:
    name: '{{ acme_tiny__user_name }}'
    group: '{{ acme_tiny__user_group }}'
    system: True
    home: '{{ acme_tiny__user_home }}'
    createhome: yes

- name: Ansible configuration
  template:
    src: 'ansible.cfg.j2'
    dest: '{{ acme_tiny__user_home }}/.ansible.cfg'
    owner: '{{ acme_tiny__user_name }}'
    group: '{{ acme_tiny__user_group }}'
    mode: '0644'

- name: Configuration directory
  file:
    path: '{{ acme_tiny__config_dir }}'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Challenge and logging directory
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ acme_tiny__user_name }}'
    group: '{{ acme_tiny__user_group }}'
    mode: '0755'
  with_items:
    - '{{ acme_tiny__challenge_dir }}'
    - '{{ acme_tiny__log_dir }}'

- name: Certificate directory
  file:
    path: '{{ acme_tiny__cert_dir }}'
    state: directory
    owner: '{{ acme_tiny__user_name }}'
    group: '{{ acme_tiny__user_group }}'
    mode: '0755'

- name: Account key permissions
  file:
    path: '{{ acme_tiny__config_dir }}/{{ acme_tiny__account_key }}'
    owner: 'root'
    group: '{{ acme_tiny__user_group }}'
    mode: '0640'

- name: Download letsencrypt CA and intermediate certificates
  get_url:
    url: '{{ item.url }}'
    dest: '{{ acme_tiny__config_dir }}/{{ item.file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ acme_tiny__ca_chain }}"

- name: Private key
  shell: /usr/bin/openssl genrsa '{{ acme_tiny__key_length }}' > '{{ acme_tiny__private_key }}'
  args:
    creates: '{{ acme_tiny__private_key }}'

- name: Private key permissions
  file:
    path: '{{ acme_tiny__private_key }}'
    owner: 'root'
    group: '{{ acme_tiny__user_group }}'
    mode: '0640'

- name: Certificate request
  shell: '/usr/bin/openssl req -new -sha256 -key {{ acme_tiny__private_key }} -subj "/CN={{ acme_tiny__domain }}" > {{ acme_tiny__cert_request }}'
  args:
    creates: '{{ acme_tiny__cert_request }}'
  when: acme_tiny__domain is string

- name: Multi-domain certificate request
  shell: '/usr/bin/openssl req -new -sha256 -key {{ acme_tiny__private_key }} -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:{{ acme_tiny__domain | join(",DNS:") }}")) > {{ acme_tiny__cert_request }}'
  args:
    executable: '/bin/bash'
    creates: '{{ acme_tiny__cert_request }}'
  when: acme_tiny__domain is iterable and not acme_tiny__domain is string
  failed_when: False

- name: Prepare certificate symlinks
  include: setup_links.yml
  when: acme_tiny__symlinks|d(True) and
        acme_tiny__service|d()

- name: Sudo rule for service restart
  template:
    src: sudoers.d-rule.j2
    dest: '/etc/sudoers.d/{{ acme_tiny__user_name }}-{{ item }}-{{ acme_tiny__cert_name | replace(".", "_") }}'
    owner: 'root'
    group: 'root'
    mode: '0440'
  when: (item in acme_tiny__service_map|d({})) and
        ("restart_command" in acme_tiny__service_map[item]) and
        (acme_tiny__service_map[item].restart_command | search("sudo"))
  with_items: '{{ acme_tiny__service
                  if acme_tiny__service is iterable and not acme_tiny__service is string
                  else [ acme_tiny__service ] }}'
