---

- name: Service SSL directory
  file:
    path: '{{ acme_tiny__service_map[item].cert_dir
              if "cert_dir" in acme_tiny__service_map[item]
              else "/etc/" + item + "/ssl" }}'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: item in acme_tiny__service_map.keys()
  with_items: '{{ acme_tiny__service
                  if acme_tiny__service is iterable and not acme_tiny__service is string
                  else [ acme_tiny__service ] }}'

- name: RSA private key links
  file:
    src: '{{ acme_tiny__private_key }}'
    path: '{{ acme_tiny__service_map[item].cert_dir
              if "cert_dir" in acme_tiny__service_map[item]
              else "/etc/" + item + "/ssl" }}/{{ acme_tiny__cert_name }}.key'
    state: link
    force: yes
  when:
    - item in acme_tiny__service_map.keys()
    - ('cert_format' in acme_tiny__service_map[item].keys())
    - not acme_tiny__service_map[item].cert_format == 'keycert'
  with_items: '{{ acme_tiny__service
                  if acme_tiny__service is iterable and not acme_tiny__service is string
                  else [ acme_tiny__service ] }}'

- name: Service certificate links
  file:
    src: '{{ acme_tiny__certificate }}'
    path: '{{ acme_tiny__service_map[item].cert_dir
              if "cert_dir" in acme_tiny__service_map[item]
              else "/etc/" +  item + "/ssl" }}/{{ acme_tiny__cert_name }}.crt'
    state: link
    force: yes
  when:
    - item in acme_tiny__service_map.keys()
    - ('cert_format' in acme_tiny__service_map[item].keys())
    - acme_tiny__service_map[item].cert_format == 'plain'
  with_items: '{{ acme_tiny__service
                  if acme_tiny__service is iterable and not acme_tiny__service is string
                  else [ acme_tiny__service ] }}'

- name: Service certificate chain links
  file:
    src: '{{ acme_tiny__certificate | replace(".crt", "") }}_chain.crt'
    path: '/etc/{{ item }}/ssl/{{ acme_tiny__cert_name }}.crt'
    state: link
    force: yes
  when:
    - item in acme_tiny__service_map.keys()
    - ('cert_format' in acme_tiny__service_map[item].keys())
    - acme_tiny__service_map[item].cert_format == 'chain'
  with_items: '{{ acme_tiny__service
                  if acme_tiny__service is iterable and not acme_tiny__service is string
                  else [ acme_tiny__service ] }}'

- name: Service PEM file links
  file:
    src: '{{ acme_tiny__cert_dir + "/" + acme_tiny__cert_name + "_keycert.pem" }}'
    path: '/etc/{{ item }}/ssl/{{ acme_tiny__cert_name }}.pem'
    state: link
    force: yes
  when:
    - item in acme_tiny__service_map.keys()
    - ('cert_format' in acme_tiny__service_map[item].keys())
    - acme_tiny__service_map[item].cert_format == 'keycert'
  with_items: '{{ acme_tiny__service
                  if acme_tiny__service is iterable and not acme_tiny__service is string
                  else [ acme_tiny__service ] }}'
