---
- name: Prepare
  hosts: all

  # The Letsencrypt account key has to be provided by the user prior of running
  # the role. Let's fake it.
  tasks:
    - name: Create acme-tiny directory
      ansible.builtin.file:
        path: /etc/ssl/acme-tiny
        state: directory
        mode: '0755'

    - name: Create Letsencrypt account key
      community.crypto.openssl_privatekey:
        path: /etc/ssl/acme-tiny/account.key
        size: 1024
        type: RSA
        mode: '0640'

    # Use mock `acme-tiny` script to fake certificate signing process
    - name: Copy mock 'acme-tiny' to default PATH
      ansible.builtin.copy:
        src: '{{ playbook_dir }}/../../test/acme-tiny.py'
        dest: /usr/local/bin/acme-tiny
        mode: '0755'

    - name: Create python compatibility symlink
      ansible.builtin.file:
        src: /usr/bin/python3
        dest: /usr/local/bin/python
        state: link

    # Install apache2 to configure HTTPS service
    - name: Install Apache2 httpd server
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start Apache2 service
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Enable HTTPS vhost  # noqa no-changed-when
      ansible.builtin.command: '{{ item }}'
      loop:
        - 'a2ensite default-ssl'
        - 'a2enmod ssl'

    # See docs/system-configuration.rst
    - name: Configure HTTPS certificates
      ansible.builtin.lineinfile:
        path: /etc/apache2/sites-available/default-ssl.conf
        regexp: '^(\s+){{ item.key }}(\s+)'
        line: '\1{{ item.key }}\2{{ item.value }}'
        backrefs: yes
      with_dict:
        SSLCertificateFile: /etc/apache2/ssl/example.com.crt
        SSLCertificateKeyFile: /etc/apache2/ssl/example.com.key
