---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check certificate-related files
      stat:
        path: '{{ item }}'
      loop:
        - /etc/ssl/acme-tiny/example.com/example.com.key
        - /etc/ssl/acme-tiny/example.com/example.com.csr
        - /etc/ssl/acme-tiny/example.com/example.com.crt
        # apache2 service has 'cert_format: chain'
        - /etc/ssl/acme-tiny/example.com/example.com_chain.crt
      register: verify_cert_files

    - name: Private key, CSR, certificate and chain must exist
      assert:
        quiet: true
        that: '{{ item.stat.exists }}'
      loop: '{{ verify_cert_files.results }}'
      loop_control:
        label: '{{ item.stat.path }}'

    - name: Verify RSA private key
      openssl_privatekey_info:
        path: /etc/ssl/acme-tiny/example.com/example.com.key
      register: verify_register_key

    - name: Validate RSA private key
      assert:
        quiet: true
        that: verify_register_key.type == 'RSA'

    - name: Verify RSA private key permissions
      assert:
        quiet: true
        that:
          - verify_cert_files.results[0].stat.pw_name == 'root'
          - verify_cert_files.results[0].stat.gr_name == 'acmetiny'
          - verify_cert_files.results[0].stat.mode == '0640'

    - name: Verify certificate signing request
      openssl_csr_info:
        path: /etc/ssl/acme-tiny/example.com/example.com.csr
      register: verify_register_csr

    - name: Verify X509 certificates
      openssl_certificate_info:
        path: '{{ item }}'
      loop:
        - /etc/ssl/acme-tiny/example.com/example.com.crt
        - /etc/ssl/acme-tiny/example.com/example.com_chain.crt

    - name: Check HTTPS port
      uri:
        url: https://127.0.0.1:443/
        headers:
          Host: example.com
        validate_certs: no
